name: Download model from Azure and deploy model git hub packages

on:
    push:
        branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.repository_owner}}
            password: ${{secrets.GH_REGISTRY}}
    
      - name: build app and push to ghcr
        uses: docker/build-push-action@v2
        with:
            context: ./
            tags: ghcr.io/amaan/flask-pred:latest
            push: true
