name: Perform Pytest

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3
              uses: actions/setup-python@v3
              with:
                python-version: 3.11
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt
            - name: Run test with pytest
              run: pytest
